### ISSUE TITLE
ORCID publications refresh not working

### ISSUE THREAD

**Issue by episanty** [dissemin/dissemin#324]
I just uploaded two papers to my ORCID account, at http://orcid.org/0000-0003-0598-8524, but they don't appear on my Dissemin account, http://dissem.in/search?researcher=2924, even after multiple attempts to refresh the publications list.

Is the Refresh function broken? It explicitly claims to be fetching publications from ORCID.

**Comment by wetneb** [comment]
Hi @episanty, this bug is due to the fact that the Crossref API is currently not working very well:
https://twitter.com/CrossrefOrg/status/794577721292685312

**Comment by episanty** [comment]
OK, but then I'm confused. Can you explain the link between CrossRef and ORCID in more detail?

**Comment by wetneb** [comment]
@episanty For historical reasons some publications associated with an ORCID id do not show up on orcid.org but only in Crossref's metadata (this has been solved for new publications)

This happened when you logged in to the publisher's submission system with your ORCID: they know your ORCID id, so they could include it in the metadata they submit to the publisher, but this did not add the publication to your public ORCID profile. Now, when this happens, the publication should be added automatically to your profile (but it isn't retroactive).

**Comment by episanty** [comment]
I'm unsure why this was closed - the issue persists for my profile. There are still two publications in my public ORCID profile that do not appear in dissemin even after I explicitly ask it to refresh and it explicitly tells me it is fetching publications from ORCID.

To be perfectly, clear, my ORCID public profile is at http://orcid.org/0000-0003-0598-8524, and the papers in question are *Lorentz drift compensation in high harmonic generation in the soft and hard X-ray regions of the spectrum* and *Kinematic origin for near-zero energy structures in mid-IR strong field ionization*. They are there in the public profile - the explanation about how they are not added to ORCID makes absolutely no sense.

I like dissemin, I do, but frankly, if the back end is broken to this extent, I have to wonder...

**Comment by wetneb** [comment]
Dear Emilio,
Sorry about that, i should have explained my action. The problem has been solved in the new version of the platform, that we hope to roll out soon. I am sorry for the inconvenience caused by this problem on the live version. Thank you very much for your feedback, we do value it a lot!
Best,
Antonin
